"""Add id primary key to settings table

Revision ID: cff6a03aeeb1
Revises: ac605807115c
Create Date: 2025-04-30 16:51:12.205788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff6a03aeeb1'
down_revision = 'ac605807115c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_timestamp')

    op.drop_table('logs')
    with op.batch_alter_table('warnings', schema=None) as batch_op:
        batch_op.drop_index('ix_warnings_issued_at')

    op.drop_table('warnings')
    op.drop_table('music')
    op.drop_table('announcements')
    op.drop_table('forbidden_content')
    op.drop_table('themes')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_sent_at')

    op.drop_table('messages')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=2048), nullable=False))
        batch_op.add_column(sa.Column('download_time', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_downloads_downloaded_at')
        batch_op.drop_column('content_url')
        batch_op.drop_column('content_type')
        batch_op.drop_column('downloaded_at')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_updated_at')
        batch_op.drop_column('description')
        batch_op.drop_column('last_updated_by_admin_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subscribed', sa.Boolean(), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index('ix_users_joined_at')
        batch_op.drop_index('ix_users_last_active_at')
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('last_warning_at')
        batch_op.drop_column('ban_expires_at')
        batch_op.drop_column('warning_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warning_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ban_expires_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_warning_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.create_index('ix_users_last_active_at', ['last_active_at'], unique=False)
        batch_op.create_index('ix_users_joined_at', ['joined_at'], unique=False)
        batch_op.alter_column('is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('is_subscribed')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_by_admin_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'admins', ['last_updated_by_admin_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('id')

    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloaded_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('content_url', sa.TEXT(), nullable=True))
        batch_op.create_index('ix_downloads_downloaded_at', ['downloaded_at'], unique=False)
        batch_op.drop_column('download_time')
        batch_op.drop_column('url')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=True),
    sa.Column('message_text', sa.TEXT(), nullable=False),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.Column('is_broadcast', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_sent_at', ['sent_at'], unique=False)

    op.create_table('themes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('css_variables', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('icon_url', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('forbidden_content',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reported_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.INTEGER(), nullable=True),
    sa.Column('content_url', sa.TEXT(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.Column('action_taken', sa.VARCHAR(length=128), nullable=True),
    sa.Column('reported_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_url')
    )
    op.create_table('announcements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('announcement_text', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=256), nullable=True),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('source_url', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('uploaded_by_admin_id', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warnings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('warning_level', sa.INTEGER(), nullable=True),
    sa.Column('issued_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warnings', schema=None) as batch_op:
        batch_op.create_index('ix_warnings_issued_at', ['issued_at'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=True),
    sa.Column('action_type', sa.VARCHAR(length=128), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('target_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index('ix_logs_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
